name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # https://github.com/actions/setup-java
      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/
          key: ${{ runner.OS }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.OS }}-maven-${{ hashFiles('pom.xml') }}-
            ${{ runner.OS }}-maven-
            ${{ runner.OS }}-

      - name: Build
        run: mvn package --file pom.xml -Pfast
      - name: Tests
        run: mvn install -PskipStyle,skipITs
      # https://app.codecov.io/gh/solven-eu/cleanthat/new
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Spotless Check
        # https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html#example-1
        # https://stackoverflow.com/questions/55657835/is-there-a-way-to-push-changes-with-a-github-action
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          mvn spotless:check || mvn spotless:apply && git commit -m "mvn spotless:apply" && git push